services:
  - type: web
    name: derma-guide-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        fromDatabase:
          name: derma-guide-db
          property: connectionString
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false

databases:
  - name: derma-guide-db
    plan: free
    databaseName: derma
    user: derma
