import os
import random
import json
import urllib.request
import base64
from datetime import datetime, timedelta
from dotenv import load_dotenv

load_dotenv()

# We no longer need SMTP_EMAIL/PASSWORD for the logic, but we can keep it for fallback/mocking logic
SMTP_EMAIL = os.getenv("SMTP_EMAIL")

# The URL generated by Google Apps Script
GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxR8lp9hP0D2ODKQtx1CfaPslbPriOOgVtS7cRx8Hxy37wS1_cjTRy3p7Ir0Tljd0CFuA/exec"

def generate_otp():
    return str(random.randint(100000, 999999))

def _send_http_email(payload: dict):
    """Helper function to send the email via Google Apps Script over HTTP"""
    try:
        req = urllib.request.Request(
            GOOGLE_SCRIPT_URL,
            data=json.dumps(payload).encode('utf-8'),
            headers={'Content-Type': 'application/json'},
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=15) as response:
            result = response.read().decode()
            print("Email sent via Apps Script:", result)
    except Exception as e:
        print(f"Error sending email via HTTP: {e}")

def send_otp_email(to_email: str, otp: str):
    if not SMTP_EMAIL:
        print(f"Mock Email sent to {to_email}. OTP: {otp}")
        return

    body = f"""Hello,

Your verification code for Derma Guide is: {otp}

This code will expire in 10 minutes.

Best,
Derma Guide Team"""

    payload = {
        "to": to_email,
        "subject": "Derma Guide - Your Verification Code",
        "body": body
    }
    
    _send_http_email(payload)

def send_pdf_email(to_email: str, pdf_path: str):
    if not SMTP_EMAIL:
        print(f"Mock Email sent to {to_email} with PDF {pdf_path}")
        return
        
    body = """Hello,

Please find attached your recent Derma Guide AI Skin Analysis report.

Important: This report is generated by an AI and is NOT a medical diagnosis. 
Always consult a healthcare professional for medical concerns.

Best,
Derma Guide Team"""
    
    pdf_base64 = None
    try:
        with open(pdf_path, 'rb') as f:
            pdf_data = f.read()
            pdf_base64 = base64.b64encode(pdf_data).decode('utf-8')
    except Exception as e:
        print(f"Error reading PDF: {e}")

    payload = {
        "to": to_email,
        "subject": "Derma Guide - Your Analysis Report",
        "body": body,
        "pdf_base64": pdf_base64
    }
    
    _send_http_email(payload)

def send_welcome_email(to_email: str, name: str):
    if not SMTP_EMAIL:
        print(f"Mock Welcome Email sent to {to_email}")
        return
        
    body = f"""Hello {name},

Welcome to Derma Ai! 

Derma Ai is an intelligent assistant designed to help you analyze skin conditions using advanced AI technology. Our goal is to provide you with preliminary insights and help you monitor your skin health.

IMPORTANT DISCLAIMER:
Please note that Derma Ai is NOT a final medical solution, diagnostic tool, or a substitute for professional medical advice. The analysis provided by the application is for informational purposes only. You still need a doctor's advisory and a professional clinical diagnosis for any medical concerns or skin conditions. Always consult a healthcare professional before making any medical decisions.

Thank you for joining us!

Warm regards,
Derma Ai Team"""

    html_body = f"""
<div style="font-family: sans-serif; color: #333; line-height: 1.6; text-align: left;">
    <p>Hello {name},</p>
    
    <p>Welcome to Derma Ai!</p>
    
    <p>Derma Ai is an intelligent assistant designed to help you analyze skin conditions using advanced AI technology. Our goal is to provide you with preliminary insights and help you monitor your skin health.</p>
    
    <div style="text-align: center; margin: 30px 0;">
        <strong style="color: black; font-weight: bold;">
            IMPORTANT DISCLAIMER:<br>
            Please note that Derma Ai is NOT a final medical solution, diagnostic tool, or a substitute for professional medical advice.<br>
            The analysis provided by the application is for informational purposes only.<br>
            You still need a doctor's advisory and a professional clinical diagnosis for any medical concerns or skin conditions.<br>
            Always consult a healthcare professional before making any medical decisions.
        </strong>
    </div>
    
    <p>Thank you for joining us!</p>
    
    <p>Warm regards,<br>Derma Ai Team</p>
</div>
"""

    payload = {
        "to": to_email,
        "subject": "Welcome to Derma Ai!",
        "body": body,
        "htmlBody": html_body
    }
    
    _send_http_email(payload)


