import smtplib
from email.message import EmailMessage
import os
import random
from datetime import datetime, timedelta
from dotenv import load_dotenv

load_dotenv()

SMTP_EMAIL = os.getenv("SMTP_EMAIL")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

def generate_otp():
    return str(random.randint(100000, 999999))

def send_otp_email(to_email: str, otp: str):
    if not SMTP_EMAIL or not SMTP_PASSWORD:
        print(f"Mock Email sent to {to_email}. OTP: {otp}")
        return

    msg = EmailMessage()
    msg['Subject'] = 'Derma Guide - Your Verification Code'
    msg['From'] = f'"Derma Guide AI" <{SMTP_EMAIL}>'
    msg['To'] = to_email
    
    msg.set_content(f"""
    Hello,
    
    Your verification code for Derma Guide is: {otp}
    
    This code will expire in 10 minutes.
    
    Best,
    Derma Guide Team
    """)

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(SMTP_EMAIL, SMTP_PASSWORD)
            smtp.send_message(msg)
    except Exception as e:
        print(f"Error sending OTP email: {e}")

def send_pdf_email(to_email: str, pdf_path: str):
    if not SMTP_EMAIL or not SMTP_PASSWORD:
        print(f"Mock Email sent to {to_email} with PDF {pdf_path}")
        return
        
    msg = EmailMessage()
    msg['Subject'] = 'Derma Guide - Your Analysis Report'
    msg['From'] = f'"Derma Guide AI" <{SMTP_EMAIL}>'
    msg['To'] = to_email
    
    msg.set_content("""
    Hello,
    
    Please find attached your recent Derma Guide AI Skin Analysis report.
    
    Important: This report is generated by an AI and is NOT a medical diagnosis. 
    Always consult a healthcare professional for medical concerns.
    
    Best,
    Derma Guide Team
    """)
    
    with open(pdf_path, 'rb') as f:
        pdf_data = f.read()
        
    msg.add_attachment(pdf_data, maintype='application', subtype='pdf', filename='DermaGuide_Report.pdf')
    
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(SMTP_EMAIL, SMTP_PASSWORD)
        smtp.send_message(msg)
